export const SEARCH_CITIES = 'SEARCH_CITIES';
export const OPEN_SEARCH_CITIES = 'OPEN_SEARCH_CITIES';
export const CLOSE_SEARCH_CITIES = 'CLOSE_SEARCH_CITIES';
export const SET_LOADING = 'SET_LOADING';
export const CITY_NOT_FOUND = 'CITY_NOT_FOUND';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const LOAD_CITIES = 'LOAD_CITIES';
